### ISSUE TITLE
ausencia de Camila-Parada

### ISSUE THREAD

**Issue by montoyamoraga** [disenoUDP/dis9034-2024-1#112]
@Camila-Parada no viniste a clase,
no tengo ningún registro de por qué faltaste,
pero estás trabajando en github, qué está pasando?
justificaste tu ausencia de la solemne??
cc @janisepulveda

**Comment by Camila-Parada** [comment]
Buenas tardes estimad@:
Hoy no asistí a clase dado que me dio un ataque de ansiedad.
Mi salud mental se encuentra delicada y estos episodios se hacen más frecuentes ( ;´ - `;). 
Mañana tengo una hora médica para tratar este asunto.
Por otra parte no quise dejar el trabajo de lado, así que hice lo que pude en cuánto a la entrega.
Apenas pueda enviaré un correo adjuntando el ingreso de un justificativo de mi inasistencia.

**Comment by montoyamoraga** [comment]
hola @Camila-Parada,
lo siento muchísimo :( espero que estés mejor,

pero tengo que decirte que es una muy mala práctica que no vengas y no avises,
y según entiendo que por reglamento debería no evaluarte por inasistencia,
pero no quiero hacer eso!

por favor sigue el protocolo de la escuela y envía tu justificativo a
secretaría de estudios!

y siempre etíquetame así @montoyamoraga 
para que me llegue la notificación más explícita

ojalá que estés mejor y gracias por contestar!
