### ISSUE TITLE
consulta sobre nf()

### ISSUE THREAD

**Issue by jacinta000** [disenoUDP/dis9034-2024-1#204]
@montoyamoraga y @janisepulveda 
Hola!!
quiero hacer una animacion con fotogramas
para eso me estoy referenciando de este proyecto
https://editor.p5js.org/stungeye/sketches/zEMpTwHvu
aqui aparece una funcion llamada nf() que no logro comprender, me ayudan?
saludos!!

**Comment by montoyamoraga** [comment]
nf es para decirle al compu que quieres tomar un numero
y convertirlo a string y agregar los 0 suficiente a la izquierda
para que todos los numeros ocupen el mismo numero de caracteres
onda si digo que los numeros tengan 5 de largo, serian
00000
00001
00002

y eso hace mas facil trabajar con ciertas estructuras de fotogramas
