### ISSUE TITLE
borrar branch extra de janice

### ISSUE THREAD

**Issue by montoyamoraga** [disenoUDP/dis9034-2024-1#69]
hola @janisepulveda por favor ayudarme con arreglar en clases
el repo de @Janiceeileen1, tiene un branch extra que se llama
patch-1 por haber tratado de hacer modificaciones desde mi repo
y no desde su fork
es llegar y borrar, ya revisé que los cambios ya están incorporados
en mi repo

**Comment by janisepulveda** [comment]
Listo !
